// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("AIT GmbH & Co. KG")]
[assembly: AssemblyProductAttribute("AIT.Tools.VisualStudioTextTransform")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015, AIT GmbH & Co. KG")]
[assembly: AssemblyVersionAttribute("1.3.0")]
[assembly: AssemblyFileVersionAttribute("1.3.0")]
[assembly: AssemblyInformationalVersionAttribute("1.3.0-alpha1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.3.0";
    }
}
